apiVersion: v1
kind: PersistentVolume
metadata:
  name: moodle-pv-volume
spec:
  storageClassName: default
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
 # hostPath:
 #   path: "/mnt/data"



