apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-sts
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: "mysql-svc"
  replicas: 1 
  template:
    metadata:
      labels:
        app: mysql
    spec:
      #terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
             secretKeyRef:
                  name: secret-pass
                  key: password
        - name: MYSQL_DATABASE
          value: "moodle"
        #- name: MYSQL_USER
        #  value: "moodle"
        #- name: MYSQL_PASSWORD
        #  valueFrom:
        #     secretKeyRef:
        #          name: secret-pass
        #          key: password
        #- name: MYSQL_INITDB_SKIP_TZINFO
        #  value: "yes"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-pvc
          mountPath: /var/lib/mysql
          subPath: "mysql"
  volumeClaimTemplates:
  - metadata:
      name: mysql-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      #storageClassName: internal-assessment
      resources:
        requests:
          storage: 5Gi


